// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhfuIP35T6_jz7arCgvH6XzMDdi-yAImw',
    appId: '1:451419751438:web:5de8fee2913e011e57285f',
    messagingSenderId: '451419751438',
    projectId: 'newpark-b43a5',
    authDomain: 'newpark-b43a5.firebaseapp.com',
    storageBucket: 'newpark-b43a5.appspot.com',
    measurementId: 'G-ZH1C16P435',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAysfquudwooHmazM1za82Iyiivx4NKfE8',
    appId: '1:451419751438:android:4274830aef6cf36557285f',
    messagingSenderId: '451419751438',
    projectId: 'newpark-b43a5',
    storageBucket: 'newpark-b43a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgvDFTCaxsKn3SOvtn3EvC9i9zi3B6qVY',
    appId: '1:451419751438:ios:eb88572c151fb9c457285f',
    messagingSenderId: '451419751438',
    projectId: 'newpark-b43a5',
    storageBucket: 'newpark-b43a5.appspot.com',
    iosClientId: '451419751438-0ca8tclui7hq6kqocnhu05ahsc861ptd.apps.googleusercontent.com',
    iosBundleId: 'com.example.newpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgvDFTCaxsKn3SOvtn3EvC9i9zi3B6qVY',
    appId: '1:451419751438:ios:4ddf6f111d0db9f457285f',
    messagingSenderId: '451419751438',
    projectId: 'newpark-b43a5',
    storageBucket: 'newpark-b43a5.appspot.com',
    iosClientId: '451419751438-4o2aoaessc5jldhnbd04dhcegpfuvfbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newpark.RunnerTests',
  );
}
